import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthenticationWrapper from "@/components/AuthenticationWrapper";

import { Shell } from "@/components/Shell/Shell";
import "@mantine/charts/styles.css";
import { ColorSchemeScript, createTheme, MantineProvider } from "@mantine/core";
import "@mantine/core/styles.css";
import { Notifications } from "@mantine/notifications";
import "@mantine/notifications/styles.css";

const myTheme = createTheme({
  primaryColor: 'blue',
  defaultRadius: 0,
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript defaultColorScheme="dark" />
      </head>
      <body className={inter.className}>
        <MantineProvider defaultColorScheme="dark" theme={myTheme}>
          <Notifications />
          <AuthenticationWrapper>
            <Shell>{children}</Shell>
          </AuthenticationWrapper>
        </MantineProvider>
      </body>
    </html>
  );
}
