import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthenticationWrapper from "@/components/AuthenticationWrapper";

import { Shell } from "@/components/Shell/Shell";
import "@mantine/charts/styles.css";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import "@mantine/core/styles.css";
import { Notifications } from "@mantine/notifications";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript forceColorScheme="light" />
      </head>
      <body className={inter.className}>
        <MantineProvider forceColorScheme="light">
          <Notifications />
          <AuthenticationWrapper>
            <Shell>{children}</Shell>
          </AuthenticationWrapper>
        </MantineProvider>
      </body>
    </html>
  );
}
