<?php
$systemoveUrl=array();
$systemoveUrl["/?modul=Administrace"]="administrace/";
$systemoveUrl["/?modul=aUzivatele"]="administrace/uzivatele/";
$systemoveUrl["/?modul=aSmazaniUzivatele"]="administrace/uzivatele/smazani-uzivatele/";
$systemoveUrl["/?modul=aNastaveni"]="administrace/nastaveni/";
$systemoveUrl["/?modul=aPromenneNastaveni"]="administrace/nastaveni/promenne-nastaveni/";
$systemoveUrl["/?modul=Uvod"]="uvod/";
$systemoveUrl["/?modul=Sitemapa"]="404/";
$systemoveUrl["/?modul=Sitemapa&akce=robots"]="robots.txt";
