<?php
global $systemoveUrl;
$systemoveUrl["/?modul=aZarizeni&akce=vypis-zarizeni"]="administrace/zarizeni/hp/";
$systemoveUrl["/?modul=aZarizeni&akce=vypis-zarizeni&m=zarizeni-jiz-existuje"]="administrace/zarizeni/hp/zarizeni-jiz-existuje/";
$systemoveUrl["/?modul=aZarizeni&akce=vypis-zarizeni&m=nazev-je-kratky"]="administrace/zarizeni/hp/nazev-je-kratky/";
$systemoveUrl["/?modul=aZarizeni&akce=vypis-zarizeni&m=zadejte-uzivatele"]="administrace/zarizeni/hp/zadejte-uzivatele/";
$systemoveUrl["/?modul=aZarizeni&akce=vypis-zarizeni&m=zarizeni-vytvoreno"]="administrace/zarizeni/hp/zarizeni-vytvoreno/";
$systemoveUrl["/?modul=aZarizeni&akce=vypis-zarizeni&m=zarizeni-smazano"]="administrace/zarizeni/hp/zarizeni-smazano/";
$systemoveUrl["/?modul=aZarizeni&akce=vypis-zarizeni&m=zarizeni-nenalezeno"]="administrace/zarizeni/hp/zarizeni-nenalezeno/";
$systemoveUrl["/?modul=aZarizeni&akce=zmena-razeni&typ=vyrobni_cislo"]="administrace/zarizeni/zmena-razeni/dle-vyrobniho-cisla/";
$systemoveUrl["/?modul=aZarizeni&akce=zmena-razeni&typ=nazev"]="administrace/zarizeni/zmena-razeni/dle-nazvu/";
$systemoveUrl["/?modul=aZarizeni&akce=zmena-razeni&typ=lokalita"]="administrace/zarizeni/zmena-razeni/dle-lokality/";
$systemoveUrl["/?modul=aZarizeni&akce=zmena-vyhledavani"]="administrace/zarizeni/zmena-vyhledavani/";
$systemoveUrl["/?modul=aZarizeni&akce=pridej-zarizeni"]="administrace/zarizeni/pridat-zarizeni/";
$systemoveUrl["/?modul=aZarizeni&akce=uloz-zarizeni"]="administrace/zarizeni/ulozit-zarizeni/";
$systemoveUrl["/?modul=aZarizeni&akce=smaz-zarizeni"]="administrace/zarizeni/smazat-zarizeni/";
$systemoveUrl["/?modul=aZarizeni&akce=editace-zarizeni"]="administrace/zarizeni/editace-zarizeni/";
$systemoveUrl["/?modul=aZarizeni&akce=editace-zarizeni&m=zarizeni-ulozeno"]="administrace/zarizeni/editace-zarizeni/zarizeni-ulozeno/";
$systemoveUrl["/?modul=aZarizeni&akce=editace-zarizeni&m=zarizeni-neulozeno"]="administrace/zarizeni/editace-zarizeni/zarizeni-neulozeno/";
